// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/meringu/terraform-private-registry/internal/ent/module"

	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// ModulesColumns holds the columns for the "modules" table.
	ModulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "owner", Type: field.TypeString},
		{Name: "namespace", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "provider", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "source", Type: field.TypeString},
		{Name: "downloads", Type: field.TypeInt64, Default: module.DefaultDownloads},
		{Name: "published_at", Type: field.TypeTime},
		{Name: "installation_id", Type: field.TypeInt64},
		{Name: "app_id", Type: field.TypeInt64},
		{Name: "repo_name", Type: field.TypeString},
	}
	// ModulesTable holds the schema information for the "modules" table.
	ModulesTable = &schema.Table{
		Name:        "modules",
		Columns:     ModulesColumns,
		PrimaryKey:  []*schema.Column{ModulesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// ModuleVersionsColumns holds the columns for the "module_versions" table.
	ModuleVersionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "major", Type: field.TypeInt},
		{Name: "minor", Type: field.TypeInt},
		{Name: "patch", Type: field.TypeInt},
		{Name: "tag", Type: field.TypeString},
		{Name: "module_id", Type: field.TypeInt, Nullable: true},
	}
	// ModuleVersionsTable holds the schema information for the "module_versions" table.
	ModuleVersionsTable = &schema.Table{
		Name:       "module_versions",
		Columns:    ModuleVersionsColumns,
		PrimaryKey: []*schema.Column{ModuleVersionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "module_versions_modules_version",
				Columns: []*schema.Column{ModuleVersionsColumns[5]},

				RefColumns: []*schema.Column{ModulesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ModulesTable,
		ModuleVersionsTable,
	}
)

func init() {
	ModuleVersionsTable.ForeignKeys[0].RefTable = ModulesTable
}
