// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/meringu/terraform-private-registry/internal/ent/module"
	"github.com/meringu/terraform-private-registry/internal/ent/predicate"
)

// ModuleDelete is the builder for deleting a Module entity.
type ModuleDelete struct {
	config
	predicates []predicate.Module
}

// Where adds a new predicate to the delete builder.
func (md *ModuleDelete) Where(ps ...predicate.Module) *ModuleDelete {
	md.predicates = append(md.predicates, ps...)
	return md
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (md *ModuleDelete) Exec(ctx context.Context) (int, error) {
	return md.sqlExec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (md *ModuleDelete) ExecX(ctx context.Context) int {
	n, err := md.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (md *ModuleDelete) sqlExec(ctx context.Context) (int, error) {
	var res sql.Result
	selector := sql.Select().From(sql.Table(module.Table))
	for _, p := range md.predicates {
		p(selector)
	}
	query, args := sql.Delete(module.Table).FromSelect(selector).Query()
	if err := md.driver.Exec(ctx, query, args, &res); err != nil {
		return 0, err
	}
	affected, err := res.RowsAffected()
	if err != nil {
		return 0, err
	}
	return int(affected), nil
}

// ModuleDeleteOne is the builder for deleting a single Module entity.
type ModuleDeleteOne struct {
	md *ModuleDelete
}

// Exec executes the deletion query.
func (mdo *ModuleDeleteOne) Exec(ctx context.Context) error {
	n, err := mdo.md.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &ErrNotFound{module.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mdo *ModuleDeleteOne) ExecX(ctx context.Context) {
	mdo.md.ExecX(ctx)
}
