// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Module is the predicate function for module builders.
type Module func(*sql.Selector)

// ModuleVersion is the predicate function for moduleversion builders.
type ModuleVersion func(*sql.Selector)
