// Code generated by entc, DO NOT EDIT.

package moduleversion

import (
	"github.com/meringu/terraform-private-registry/internal/ent/schema"
)

const (
	// Label holds the string label denoting the moduleversion type in the database.
	Label = "module_version"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMajor holds the string denoting the major vertex property in the database.
	FieldMajor = "major"
	// FieldMinor holds the string denoting the minor vertex property in the database.
	FieldMinor = "minor"
	// FieldPatch holds the string denoting the patch vertex property in the database.
	FieldPatch = "patch"
	// FieldTag holds the string denoting the tag vertex property in the database.
	FieldTag = "tag"

	// Table holds the table name of the moduleversion in the database.
	Table = "module_versions"
	// ModuleTable is the table the holds the module relation/edge.
	ModuleTable = "module_versions"
	// ModuleInverseTable is the table name for the Module entity.
	// It exists in this package in order to avoid circular dependency with the "module" package.
	ModuleInverseTable = "modules"
	// ModuleColumn is the table column denoting the module relation/edge.
	ModuleColumn = "module_id"
)

// Columns holds all SQL columns are moduleversion fields.
var Columns = []string{
	FieldID,
	FieldMajor,
	FieldMinor,
	FieldPatch,
	FieldTag,
}

var (
	fields = schema.ModuleVersion{}.Fields()

	// descMajor is the schema descriptor for major field.
	descMajor = fields[0].Descriptor()
	// MajorValidator is a validator for the "major" field. It is called by the builders before save.
	MajorValidator = descMajor.Validators[0].(func(int) error)

	// descMinor is the schema descriptor for minor field.
	descMinor = fields[1].Descriptor()
	// MinorValidator is a validator for the "minor" field. It is called by the builders before save.
	MinorValidator = descMinor.Validators[0].(func(int) error)

	// descPatch is the schema descriptor for patch field.
	descPatch = fields[2].Descriptor()
	// PatchValidator is a validator for the "patch" field. It is called by the builders before save.
	PatchValidator = descPatch.Validators[0].(func(int) error)
)
